[workspace]
resolver = "2"
members = [ "bin/keyshare-stats","bin/test-client", "bin/test-wasm","crates/fairblock-proto"]

[workspace.dependencies]
fairblock-proto = { path = "crates/fairblock-proto/" }
