[package]
name = "fairblock-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmos-sdk-proto = "0.23.0"
prost = "0.13.1"
prost-types = "0.13.1"
tonic = { version = "0.12.1", features = ["prost", "codegen"] }
